name: Continuos Integration

on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Run build
        run: npm run build