name: Continuos Integration

on: [pull_request, push]
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Report Coverage
        if: always() 
        uses:  davelosert/vitest-coverage-report-action@v2
      - name: Run build
        run: npm run build